### ISSUE TITLE
grouping issue in hashpipe code

### ISSUE THREAD

**Issue by liuweiseu** [panoseti/panoseti#116]
When the integration time is short, we have issues about grouping four packets from four quabos in hashpipe code.

See the metadata in this data file on the headnode:
/mnt/data10/obs_Lick.start_2022-10-12T01:34:54Z.runtype_eng.pffd/start_2022-10-12T01:35:07Z.dp_img16.bpp_2.module_254.seqno_0.pff.

The integration time is 20us in the test.

**Comment by liuweiseu** [comment]
It looks like the issue only happens when we use 16-bit IM mode with integration time=20us.

8-bit IM mode with integration time=20us doesn't have this issue.

**Comment by davidpanderson** [comment]
This happens if the data rate is close to 1 Gbps,
in which case packets arrive out of order.

We considered fixing this in hashpipe, but instead decided to prohibit
frame rates that can cause this to happen;
8 bit must be at least 20us, 16 bit must be at least 40us.

Done in e97aee7edc91d7e4cf8c5a42098f378cc7e1f3a0
