### ISSUE TITLE
document panoseti_tftp.py

### ISSUE THREAD

**Issue by davidpanderson** [panoseti/panoseti#28]
... and maybe combine it with quabo_driver.py?

**Comment by davidpanderson** [comment]
I found a doc (in a .zip file) and added it here.  It's a PDF.  We need to replace it with something that can be edited.

**Comment by liuweiseu** [comment]
It looks good to combine panoseti_tftp.py with quabo_driver.py, so that we can finish any operations with quabo_driver.py.

I also have a word version of the documen, which is attached
[Panoseti_TFTP_PythonPackage_User_Manual_V1.0.1.zip](https://github.com/panoseti/panoseti/files/7927711/Panoseti_TFTP_PythonPackage_User_Manual_V1.0.1.zip)
.
