### ISSUE TITLE
Get both sec and nanosec time from white rabbit

### ISSUE THREAD

**Issue by davidpanderson** [panoseti/panoseti#5]

**Comment by liuweiseu** [comment]
In the latest firmware (V0200 and V0201), TAI time is added to IM packets and PH packets.
The information about TAI time is here: http://leapsecond.com/java/gpsclock.htm

Only quabo0 is connected to the WR network, and it transmits timing and frequency information to the other three quabos on the same mobo. 

The full TAI time from WR is a 40-bit value.
Because we don't have enough pin to transmit the full TAI time from quabo0 to quabo1/2/3, we only transmitted the least 10-bit value to quabo1/2/3. Therefore, only 10 bits are valid in IM and PH packets.
